### ISSUE TITLE
JavaScript: Convert index to drop-down menu

### ISSUE THREAD

**Issue by espimadrazo** [0ka3ri/uncanny-page#12]
@mauriciopasquier Since I'm considering making a home page with nothing but a small description, I'm thinking about turning the index into a drop-down menu on the header. Would you say this is a functional idea? I don't know what would happen if there ends up being A LOT of titles though, the index might become a little too long and awkward to use on that specific format.

**Comment by mauriciopasquier** [comment]
Are you thinking of a single index.html for the home page and then subsequent html files for the individual pages? You could have the first level (i.e. the pages) to start with, and leave the subsections for an index menu inside each page :thinking:

**Comment by espimadrazo** [comment]
I've already started, check out the pull request (:
