### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by espimadrazo** [0ka3ri/uncanny-page#17]

**Comment by espimadrazo** [comment]
@mauriciopasquier I'm ready to address this whenever you are.

**Comment by mauriciopasquier** [comment]
> @mauriciopasquier I'm ready to address this whenever you are.

Awesome!

**Comment by mauriciopasquier** [comment]
I think a prerequisite for this issue could be changing the paths to absolute based on the URL/webserver root. What I mean, for example, is changing this:

```HTML
  <link rel="stylesheet" href="../../style.css">
  <link rel="stylesheet" href="../../styles/responsive.css">
```

to this:

```HTML
  <link rel="stylesheet" href="/style.css">
  <link rel="stylesheet" href="/styles/responsive.css">
```

The same with all the internal links. This change makes the references more tolerant to changes in structure.. i.e. if you decide to move every page to new subdirectory, adding a level, you don't need to change the paths.

(Regarding this specific example though, I would put `style.css` inside the `styles` folder named "base", "main" or something like that).

**Comment by espimadrazo** [comment]
Okey dokey. 

Oh, I thought the convention for the css is to always name the main style sheet "style.css" and use a specific name for other things. Or are you saying that `style.css` should be in its own folder inside the `styles` folder?

**Comment by espimadrazo** [comment]
So, to see if I finally got this... By mounting a server on a folder you're also establishing that folder is now the root **of the server**, and that's why absolute paths can work "objectively" even when you don't have the files in your computer, because the files do exist on the server. Right? 

I don't know why this messed up my brain so much.

**Comment by mauriciopasquier** [comment]
> So, to see if I finally got this... By mounting a server on a folder you're also establishing that folder is now the root **of the server**, and that's why absolute paths can work "objectively" 

Yes! Because the webserver, local or "in the cloud" sets up a folder as the root, and it serves everything based on that root. So a "/file" in your local folders goes to the root ("/" of the filesystem) but when accessed through the webserver goes to the root configured for the webserver.

> even when you don't have the files in your computer, because the files do exist on the server. Right?

No, the files do exist on your computer (or the computer where the server is running, be it local or remote), it's just that you access the files through the server and the server restricts everything so it starts from the configured root.

**Comment by mauriciopasquier** [comment]
> Okey dokey.
> 
> Oh, I thought the convention for the css is to always name the main style sheet "style.css" and use a specific name for other things. Or are you saying that `style.css` should be in its own folder inside the `styles` folder?

I don't know about that convention :thinking: 
I'm saying it's best to have all the css in the same folder. It doesn't reaaaally matter how you name the main stylesheet as long as you know it is the main one.

**Comment by mauriciopasquier** [comment]
We need to coordinate a date/time to be able to move forward with this, we'll do a deployment workshop.

**Comment by espimadrazo** [comment]
Okay Mauricio senpai, workshops are my passion. 
I'll be checking domain costs.

**Comment by mauriciopasquier** [comment]
> Okay Mauricio senpai, workshops are my passion. I'll be checking domain costs.

No domain costs! Just deployment

**Comment by mauriciopasquier** [comment]
We can close this and work on #31 for the next improvement :)
