### ISSUE TITLE
Reset styles

### ISSUE THREAD

**Issue by mauriciopasquier** [0ka3ri/uncanny-page#4]
Something to consider when you are working on plain HTML + CSS (i.e. without frameworks or libraries) is adding a reset stylesheet, to unify looks across browsers. Maybe in modern days it is not that needed anymore, but if you're curious [this](http://meyerweb.com/eric/thoughts/2007/04/18/reset-reasoning/) is a good article about why they were used, and [here](https://www.joshwcomeau.com/css/custom-css-reset/) is a more lightweight, modern approach (check out "A pedantic note" there).

**Comment by espimadrazo** [comment]
It's good to know this exists and that browser actually have small style differences, I think for now I'm going to go for the default though.

**Comment by mauriciopasquier** [comment]
Makes sense!
